### ISSUE TITLE
Role name not working/displayed on movie profile

### ISSUE THREAD

**Issue by aswinshenoy** [aswinshenoy/django-moviedb#1]
Role name is not being displayed on movie profile (template/movie/single.html)
`        <div class="font-weight-bold"> {{artist.role_name}} </div>
`

**Comment by aswinshenoy** [comment]
`role_name` is a field of the `roles` model and is not directly accessible from the many-to-many field `artists`. It can be fixed by the following code, which uses `roles_set` to access the many-to-many relation.
```
{% for artist in movie.roles_set.all %}
    <div class="col-md-3 col-sm-6 p-2">
      <div class="card p-2">
        <h2 class="m-0"> {{artist.artist.name}} </h2>
        <div class="font-weight-bold"> {{artist.role_name}} </div>
        <a href="/artist/{{artist.artist.id}}/" class="btn btn-primary">View</a>
      </div>
    </div
  {% endfor %}
```

**Comment by jyothiprakashk** [comment]
Hiiii @aswinshenoy what is purpose of this app and there is no api how can you do this plz explain about this django app
